fails:The break statement in a block returns nil to method invoking the method yielding to the block when not passed an argument
fails:The break statement in a block returns a value to the method invoking the method yielding to the block
fails:The break statement in a block yielded inside a while breaks out of the block
fails:The break statement in a block captured and delegated to another method repeatedly breaks out of the block
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when invoking the block from the scope creating the block
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when invoking the block from a method
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when yielding to the block
fails:The break statement in a captured block from a scope that has returned raises a LocalJumpError when calling the block from a method
fails:The break statement in a captured block from a scope that has returned raises a LocalJumpError when yielding to the block
fails:The break statement in a captured block from another thread raises a LocalJumpError when getting the value from another thread
fails:The break statement in a lambda returns from the lambda
fails:The break statement in a lambda returns from the call site if the lambda is passed as a block
fails:The break statement in a lambda when the invocation of the scope creating the lambda is still active returns nil when not passed an argument
fails:The break statement in a lambda when the invocation of the scope creating the lambda is still active returns a value to the scope creating and calling the lambda
fails:The break statement in a lambda when the invocation of the scope creating the lambda is still active returns a value to the method scope below invoking the lambda
fails:The break statement in a lambda when the invocation of the scope creating the lambda is still active returns a value to a block scope invoking the lambda in a method below
fails:The break statement in a lambda created at the toplevel returns a value when invoking from the toplevel
fails:The break statement in a lambda created at the toplevel returns a value when invoking from a method
fails:The break statement in a lambda created at the toplevel returns a value when invoking from a block
fails:The break statement in a lambda from a scope that has returned returns a value to the method scope invoking the lambda
fails:The break statement in a lambda from a scope that has returned returns a value to the block scope invoking the lambda in a method
fails:Break inside a while loop causes a call with a block to return when run
fails:Break inside a while loop with a value passes the value returned by a method with omitted parenthesis and passed block
fails:Break inside a while loop with a splat wraps a non-Array in an Array
fails:Executing break from within a block returns from the original invoking method even in case of chained calls
fails:Executing break from within a block runs ensures when continuing upward
fails:Executing break from within a block doesn't run ensures in the destination method
